language: java

services:
  - docker

before_install:
  - nvm install 12

install:
  - cd med-web-app-front
  - npm install

before_script:
  - cd ../src/main/docker/postgres
  - docker build -t medwebpostgres .
  - cd ../../../../med-web-app-front
  - npm run build
  - cd ..

script:
  - docker run -d --name sftp           -p 4999:22   --rm atmoz/sftp  medwebuser:secretpassword:::upload
  - docker run -d --name medwebpostgres -p 5555:5555 --rm medwebpostgres
  - docker run -d --name ortanc         -p 8042:8042 --rm jodogne/orthanc
  - mvn package

after_success:
  - mvn compile jib:build -Djib.to.auth.username=$DOCKER_ID -Djib.to.auth.password=$DOCKER_PASSWORD

branches:
  only:
    - master
